name: "Generate monthly report for on-call"
on:
  # Necessary to test the workflow on PRs.
  pull_request:
  # Send on push so that the on-call get an updated report, if needed.
  push:
    branches:
      - master
  schedule:
    # Run every Monday at 9am PST
    - cron:  '0 15 * * MON'

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:bionic
    steps:
    - uses: actions/checkout@v2.3.1
    - uses: ros-security/github-contribution-report-generator@0.0.7
      with:
        authors-filter: |
          AAlon
          adam-dunc
          brandonpelfrey
          cevans87
          dabonnie
          emersonknapp
          gauravgh
          jaisontj
          juanrh
          lichenbo
          mm318
          murphm8
          nburek
          piraka9011
          prajakta-gokhale
          r-meagher
          raghaprasad
          ross-desmond
          rutvih
          ryanewel
          samuelgundry
          thomas-moulard
          timrobotson
          xabxx
          yyu
          zmichaels11
        organizations-filter: |
          ament
          colcon
          ros
          ros-infrastructure
          ros-security
          ros-tooling
          ros2
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        since-n-days-ago: 30
        file-name: monthly-report
    - uses: actions/upload-artifact@2.1.0
      with:
        name: html-report
        path: monthly-report.html
    - uses: actions/upload-artifact@2.1.0
      with:
        name: markdown-report
        path: monthly-report.md
