name: "Report usage metrics for monitored repositories"
on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 * * * *'  # run every hour

jobs:
  repo_activity:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:bionic
    strategy:
      fail-fast: false
      matrix:
        repo:
        - colcon/colcon-bundle
        - colcon/colcon-ros-bundle
        - colcon/colcon-sanitizer-reports
        - ros-tooling/action-amazon-chime
        - ros-tooling/action-pypi
        - ros-tooling/action-ros-ci-template
        - ros-tooling/cross_compile
        - ros-tooling/github-contribution-report-generator
        - ros-tooling/aws-oncall
        - ros-tooling/action-repository-activity
        - ros-tooling/action-ros-lint
        - ros-tooling/action-ros-ci
        - ros-tooling/setup-ros
        - ros-tooling/launch_ros_sandbox
        - ros-tooling/system_metrics_collector
        - ros-tooling/libstatistics_collector
        - ros2/rosbag2
        - ros2/rosbag2_bag_v2
        - aws-robotics/cloudwatch-common
        - aws-robotics/cloudwatchlogs-ros1
        - aws-robotics/cloudwatchlogs-ros2
        - aws-robotics/cloudwatchmetrics-ros1
        - aws-robotics/cloudwatchmetrics-ros2
        - aws-robotics/health-metrics-collector-ros1
        - aws-robotics/health-metrics-collector-ros2
        - aws-robotics/kinesisvideo-common
        - aws-robotics/kinesisvideo-encoder-common
        - aws-robotics/kinesisvideo-encoder-ros1
        - aws-robotics/kinesisvideo-encoder-ros2
        - aws-robotics/kinesisvideo-ros1
        - aws-robotics/kinesisvideo-ros2
        - aws-robotics/lex-common
        - aws-robotics/lex-ros1
        - aws-robotics/lex-ros2
        - aws-robotics/monitoringmessages-ros1
        - aws-robotics/monitoringmessages-ros2
        - aws-robotics/rosbag-uploader-ros1
        - aws-robotics/tts-ros1
        - aws-robotics/tts-ros2
        - aws-robotics/utils-common
        - aws-robotics/utils-ros1
        - aws-robotics/utils-ros2
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - uses: ros-tooling/action-repository-activity@0.0.1
      id: repo_activity
      with:
        repository: ${{ matrix.repo }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - uses: ros-tooling/action-cloudwatch-metrics@0.0.4
      with:
        metric-dimensions: >-
          [
            { "Name": "github.event_name", "Value": "${{ github.event_name }}" },
            { "Name": "github.ref", "Value": "${{ github.ref }}" },
            { "Name": "github.repository", "Value": "${{ matrix.repo }}" }
          ]
        metric-name: open_issues_count
        metric-value: ${{ steps.repo_activity.outputs.open_issues_count }}
    - uses: ros-tooling/action-cloudwatch-metrics@0.0.4
      with:
        metric-dimensions: >-
          [
            { "Name": "github.event_name", "Value": "${{ github.event_name }}" },
            { "Name": "github.ref", "Value": "${{ github.ref }}" },
            { "Name": "github.repository", "Value": "${{ matrix.repo }}" }
          ]
        metric-name: archived
        metric-value: ${{ steps.repo_activity.outputs.archived }}
    - uses: ros-tooling/action-cloudwatch-metrics@0.0.4
      with:
        metric-dimensions: >-
          [
            { "Name": "github.event_name", "Value": "${{ github.event_name }}" },
            { "Name": "github.ref", "Value": "${{ github.ref }}" },
            { "Name": "github.repository", "Value": "${{ matrix.repo }}" }
          ]
        metric-name: disabled
        metric-value: ${{ steps.repo_activity.outputs.disabled }}
    - uses: ros-tooling/action-cloudwatch-metrics@0.0.4
      with:
        metric-dimensions: >-
          [
            { "Name": "github.event_name", "Value": "${{ github.event_name }}" },
            { "Name": "github.ref", "Value": "${{ github.ref }}" },
            { "Name": "github.repository", "Value": "${{ matrix.repo }}" }
          ]
        metric-name: forks_count
        metric-value: ${{ steps.repo_activity.outputs.forks_count }}
    - uses: ros-tooling/action-cloudwatch-metrics@0.0.4
      with:
        metric-dimensions: >-
          [
            { "Name": "github.event_name", "Value": "${{ github.event_name }}" },
            { "Name": "github.ref", "Value": "${{ github.ref }}" },
            { "Name": "github.repository", "Value": "${{ matrix.repo }}" }
          ]
        metric-name: network_count
        metric-value: ${{ steps.repo_activity.outputs.network_count }}
    - uses: ros-tooling/action-cloudwatch-metrics@0.0.4
      with:
        metric-dimensions: >-
          [
            { "Name": "github.event_name", "Value": "${{ github.event_name }}" },
            { "Name": "github.ref", "Value": "${{ github.ref }}" },
            { "Name": "github.repository", "Value": "${{ matrix.repo }}" }
          ]
        metric-name: open_issues_count
        metric-value: ${{ steps.repo_activity.outputs.open_issues_count }}
    - uses: ros-tooling/action-cloudwatch-metrics@0.0.4
      with:
        metric-dimensions: >-
          [
            { "Name": "github.event_name", "Value": "${{ github.event_name }}" },
            { "Name": "github.ref", "Value": "${{ github.ref }}" },
            { "Name": "github.repository", "Value": "${{ matrix.repo }}" }
          ]
        metric-name: stargazers_count
        metric-value: ${{ steps.repo_activity.outputs.stargazers_count }}
    - uses: ros-tooling/action-cloudwatch-metrics@0.0.4
      with:
        metric-dimensions: >-
          [
            { "Name": "github.event_name", "Value": "${{ github.event_name }}" },
            { "Name": "github.ref", "Value": "${{ github.ref }}" },
            { "Name": "github.repository", "Value": "${{ matrix.repo }}" }
          ]
        metric-name: subscribers_count
        metric-value: ${{ steps.repo_activity.outputs.subscribers_count }}
    - uses: ros-tooling/action-cloudwatch-metrics@0.0.4
      with:
        metric-dimensions: >-
          [
            { "Name": "github.event_name", "Value": "${{ github.event_name }}" },
            { "Name": "github.ref", "Value": "${{ github.ref }}" },
            { "Name": "github.repository", "Value": "${{ matrix.repo }}" }
          ]
        metric-name: watchers_count
        metric-value: ${{ steps.repo_activity.outputs.watchers_count }}
